// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/postgres/uow/uow.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uow "github.com/Fi44er/sdmed/pkg/postgres/uow"
	gomock "github.com/golang/mock/gomock"
)

// MockUow is a mock of Uow interface.
type MockUow struct {
	ctrl     *gomock.Controller
	recorder *MockUowMockRecorder
}

// MockUowMockRecorder is the mock recorder for MockUow.
type MockUowMockRecorder struct {
	mock *MockUow
}

// NewMockUow creates a new mock instance.
func NewMockUow(ctrl *gomock.Controller) *MockUow {
	mock := &MockUow{ctrl: ctrl}
	mock.recorder = &MockUowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUow) EXPECT() *MockUowMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockUow) Begin(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockUowMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockUow)(nil).Begin), ctx)
}

// Commit mocks base method.
func (m *MockUow) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUowMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUow)(nil).Commit), ctx)
}

// Do mocks base method.
func (m *MockUow) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockUowMockRecorder) Do(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUow)(nil).Do), ctx, fn)
}

// GetRepository mocks base method.
func (m *MockUow) GetRepository(ctx context.Context, name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", ctx, name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockUowMockRecorder) GetRepository(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockUow)(nil).GetRepository), ctx, name)
}

// RegisterRepository mocks base method.
func (m *MockUow) RegisterRepository(name string, factory uow.RepositoryFactory) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRepository", name, factory)
}

// RegisterRepository indicates an expected call of RegisterRepository.
func (mr *MockUowMockRecorder) RegisterRepository(name, factory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRepository", reflect.TypeOf((*MockUow)(nil).RegisterRepository), name, factory)
}

// Rollback mocks base method.
func (m *MockUow) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockUowMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUow)(nil).Rollback), ctx)
}
