// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/module/product/usecase/category/usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	product_entity "github.com/Fi44er/sdmed/internal/module/product/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockIFileUsecaseAdapter is a mock of IFileUsecaseAdapter interface.
type MockIFileUsecaseAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIFileUsecaseAdapterMockRecorder
}

// MockIFileUsecaseAdapterMockRecorder is the mock recorder for MockIFileUsecaseAdapter.
type MockIFileUsecaseAdapterMockRecorder struct {
	mock *MockIFileUsecaseAdapter
}

// NewMockIFileUsecaseAdapter creates a new mock instance.
func NewMockIFileUsecaseAdapter(ctrl *gomock.Controller) *MockIFileUsecaseAdapter {
	mock := &MockIFileUsecaseAdapter{ctrl: ctrl}
	mock.recorder = &MockIFileUsecaseAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFileUsecaseAdapter) EXPECT() *MockIFileUsecaseAdapterMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockIFileUsecaseAdapter) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIFileUsecaseAdapterMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIFileUsecaseAdapter)(nil).DeleteByID), ctx, id)
}

// DeleteByOwner mocks base method.
func (m *MockIFileUsecaseAdapter) DeleteByOwner(ctx context.Context, ownerID, ownerType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOwner", ctx, ownerID, ownerType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByOwner indicates an expected call of DeleteByOwner.
func (mr *MockIFileUsecaseAdapterMockRecorder) DeleteByOwner(ctx, ownerID, ownerType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOwner", reflect.TypeOf((*MockIFileUsecaseAdapter)(nil).DeleteByOwner), ctx, ownerID, ownerType)
}

// GetByOwner mocks base method.
func (m *MockIFileUsecaseAdapter) GetByOwner(ctx context.Context, ownerID, ownerType string) ([]product_entity.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", ctx, ownerID, ownerType)
	ret0, _ := ret[0].([]product_entity.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockIFileUsecaseAdapterMockRecorder) GetByOwner(ctx, ownerID, ownerType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockIFileUsecaseAdapter)(nil).GetByOwner), ctx, ownerID, ownerType)
}

// GetByOwners mocks base method.
func (m *MockIFileUsecaseAdapter) GetByOwners(ctx context.Context, ownerIDs []string, ownerType string) (map[string][]product_entity.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwners", ctx, ownerIDs, ownerType)
	ret0, _ := ret[0].(map[string][]product_entity.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwners indicates an expected call of GetByOwners.
func (mr *MockIFileUsecaseAdapterMockRecorder) GetByOwners(ctx, ownerIDs, ownerType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwners", reflect.TypeOf((*MockIFileUsecaseAdapter)(nil).GetByOwners), ctx, ownerIDs, ownerType)
}

// MakeFilesPermanent mocks base method.
func (m *MockIFileUsecaseAdapter) MakeFilesPermanent(ctx context.Context, fileIDs []string, ownerID, ownerType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeFilesPermanent", ctx, fileIDs, ownerID, ownerType)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeFilesPermanent indicates an expected call of MakeFilesPermanent.
func (mr *MockIFileUsecaseAdapterMockRecorder) MakeFilesPermanent(ctx, fileIDs, ownerID, ownerType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeFilesPermanent", reflect.TypeOf((*MockIFileUsecaseAdapter)(nil).MakeFilesPermanent), ctx, fileIDs, ownerID, ownerType)
}

// MockICategoryUsecase is a mock of ICategoryUsecase interface.
type MockICategoryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockICategoryUsecaseMockRecorder
}

// MockICategoryUsecaseMockRecorder is the mock recorder for MockICategoryUsecase.
type MockICategoryUsecaseMockRecorder struct {
	mock *MockICategoryUsecase
}

// NewMockICategoryUsecase creates a new mock instance.
func NewMockICategoryUsecase(ctrl *gomock.Controller) *MockICategoryUsecase {
	mock := &MockICategoryUsecase{ctrl: ctrl}
	mock.recorder = &MockICategoryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoryUsecase) EXPECT() *MockICategoryUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICategoryUsecase) Create(ctx context.Context, category *product_entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockICategoryUsecaseMockRecorder) Create(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICategoryUsecase)(nil).Create), ctx, category)
}

// Delete mocks base method.
func (m *MockICategoryUsecase) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICategoryUsecaseMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICategoryUsecase)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockICategoryUsecase) GetAll(ctx context.Context, offset, limit int) ([]product_entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, offset, limit)
	ret0, _ := ret[0].([]product_entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICategoryUsecaseMockRecorder) GetAll(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICategoryUsecase)(nil).GetAll), ctx, offset, limit)
}

// GetByID mocks base method.
func (m *MockICategoryUsecase) GetByID(ctx context.Context, id string) (*product_entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*product_entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockICategoryUsecaseMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockICategoryUsecase)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockICategoryUsecase) Update(ctx context.Context, category *product_entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICategoryUsecaseMockRecorder) Update(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICategoryUsecase)(nil).Update), ctx, category)
}

// MockICategoryRepository is a mock of ICategoryRepository interface.
type MockICategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICategoryRepositoryMockRecorder
}

// MockICategoryRepositoryMockRecorder is the mock recorder for MockICategoryRepository.
type MockICategoryRepositoryMockRecorder struct {
	mock *MockICategoryRepository
}

// NewMockICategoryRepository creates a new mock instance.
func NewMockICategoryRepository(ctrl *gomock.Controller) *MockICategoryRepository {
	mock := &MockICategoryRepository{ctrl: ctrl}
	mock.recorder = &MockICategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoryRepository) EXPECT() *MockICategoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICategoryRepository) Create(ctx context.Context, entity *product_entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockICategoryRepositoryMockRecorder) Create(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICategoryRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockICategoryRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICategoryRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICategoryRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockICategoryRepository) GetAll(ctx context.Context, offset, limit int) ([]product_entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, offset, limit)
	ret0, _ := ret[0].([]product_entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICategoryRepositoryMockRecorder) GetAll(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICategoryRepository)(nil).GetAll), ctx, offset, limit)
}

// GetByID mocks base method.
func (m *MockICategoryRepository) GetByID(ctx context.Context, id string) (*product_entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*product_entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockICategoryRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockICategoryRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockICategoryRepository) GetByName(ctx context.Context, name string) (*product_entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*product_entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockICategoryRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockICategoryRepository)(nil).GetByName), ctx, name)
}

// Update mocks base method.
func (m *MockICategoryRepository) Update(ctx context.Context, category *product_entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICategoryRepositoryMockRecorder) Update(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICategoryRepository)(nil).Update), ctx, category)
}
